import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { readTrips, clearTrips, type TripSummary } from "@/lib/trips";
import { fmtDistance, fmtDuration } from "@/lib/format";
import { useSettings } from "@/lib/settings";
import { useAccount } from "@/lib/account";
import { supabase } from "@/integrations/supabase/client";
import { Clock, Trash2 } from "lucide-react";
export const Route = createFileRoute("/_map/history")({ head: () => ({ meta: [{ title: "Trip history & stats — Meridian" }, { name: "description", content: "Private, opt-in trip summaries and travel statistics on Meridian." }, { property: "og:title", content: "Meridian trip history" }, { property: "og:description", content: "Your recent journeys, kept on your device by default." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: History });
function History() {
  const [trips, setTrips] = useState<TripSummary[]>([]); const [message, setMessage] = useState(""); const { settings, update } = useSettings(); const { user, syncStatus } = useAccount();
  useEffect(() => { const refresh = () => setTrips(readTrips()); refresh(); window.addEventListener("meridian-trips", refresh); return () => window.removeEventListener("meridian-trips", refresh); }, []);
  return <div className="px-5 py-5"><header className="flex items-center justify-between"><h1 className="font-display text-2xl">Trips & stats</h1><Clock strokeWidth={1.5} className="text-primary" /></header><p className="mt-3 text-xs text-muted-foreground">{settings.tripHistory ? "Trip summaries only · 30-day retention" : "History is off"} · {syncStatus}</p>{!settings.tripHistory && <Button variant="outline" className="mt-4" onClick={() => update({ tripHistory: true })}>Enable on-device history</Button>}<div className="mt-6 grid grid-cols-3 gap-2 border-y py-5"><div><strong className="tnum block text-xl">{trips.length}</strong><span className="text-xs text-muted-foreground">Trips</span></div><div><strong className="tnum block text-lg">{fmtDistance(trips.reduce((n,t) => n+t.distance_m, 0), settings.units)}</strong><span className="text-xs text-muted-foreground">Distance</span></div><div><strong className="tnum block text-lg">{fmtDuration(trips.reduce((n,t) => n+t.duration_s, 0))}</strong><span className="text-xs text-muted-foreground">Travel time</span></div></div>{trips.length ? <ol className="divide-y">{trips.map(t => <li key={t.id} className="py-4"><p className="text-sm">{new Date(t.started_at).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</p><p className="mt-1 text-xs text-muted-foreground">{fmtDistance(t.distance_m, settings.units)} · {fmtDuration(t.duration_s)} · {t.completed ? "Arrived" : "Ended early"}</p></li>)}</ol> : <p className="py-8 text-sm text-muted-foreground">No trip summaries saved.</p>}<div className="flex flex-wrap gap-2"><Button asChild variant="ghost"><Link to="/auth">Account & sync</Link></Button><Button variant="ghost" onClick={async () => { if (!window.confirm("Delete all local and synced trip summaries?")) return; update({ syncTrips: false }); if (user) { const result = await supabase.from("trip_summaries").delete().eq("user_id", user.id); if (result.error) { setMessage("Cloud deletion failed. Retry while connected."); return; } await supabase.from("travel_preferences").update({ sync_opt_in: false }).eq("user_id", user.id); } clearTrips(); }}><Trash2 strokeWidth={1.5} className="h-4 w-4" /> Delete history</Button></div>{message && <p role="status" className="mt-3 text-sm text-destructive">{message}</p>}</div>;
}