/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapRouteImport } from './routes/map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as MapDirectionsRouteImport } from './routes/map/directions'
import { Route as MapOfflineRouteImport } from './routes/map/offline'
import { Route as MapPlaceIdRouteImport } from './routes/map/place.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapRoute,
} as any)
const MapDirectionsRoute = MapDirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => MapRoute,
} as any)
const MapOfflineRoute = MapOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => MapRoute,
} as any)
const MapPlaceIdRoute = MapPlaceIdRouteImport.update({
  id: '/place/$id',
  path: '/place/$id',
  getParentRoute: () => MapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRouteWithChildren
  '/settings': typeof SettingsRoute
  '/map/directions': typeof MapDirectionsRoute
  '/map/offline': typeof MapOfflineRoute
  '/map/': typeof MapIndexRoute
  '/map/place/$id': typeof MapPlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/map/directions': typeof MapDirectionsRoute
  '/map/offline': typeof MapOfflineRoute
  '/map': typeof MapIndexRoute
  '/map/place/$id': typeof MapPlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRouteWithChildren
  '/settings': typeof SettingsRoute
  '/map/directions': typeof MapDirectionsRoute
  '/map/offline': typeof MapOfflineRoute
  '/map/': typeof MapIndexRoute
  '/map/place/$id': typeof MapPlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/settings'
    | '/map/directions'
    | '/map/offline'
    | '/map/'
    | '/map/place/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/map/directions'
    | '/map/offline'
    | '/map'
    | '/map/place/$id'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/settings'
    | '/map/directions'
    | '/map/offline'
    | '/map/'
    | '/map/place/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof MapRoute
    }
    '/map/directions': {
      id: '/map/directions'
      path: '/directions'
      fullPath: '/map/directions'
      preLoaderRoute: typeof MapDirectionsRouteImport
      parentRoute: typeof MapRoute
    }
    '/map/offline': {
      id: '/map/offline'
      path: '/offline'
      fullPath: '/map/offline'
      preLoaderRoute: typeof MapOfflineRouteImport
      parentRoute: typeof MapRoute
    }
    '/map/place/$id': {
      id: '/map/place/$id'
      path: '/place/$id'
      fullPath: '/map/place/$id'
      preLoaderRoute: typeof MapPlaceIdRouteImport
      parentRoute: typeof MapRoute
    }
  }
}

interface MapRouteChildren {
  MapDirectionsRoute: typeof MapDirectionsRoute
  MapOfflineRoute: typeof MapOfflineRoute
  MapIndexRoute: typeof MapIndexRoute
  MapPlaceIdRoute: typeof MapPlaceIdRoute
}

const MapRouteChildren: MapRouteChildren = {
  MapDirectionsRoute: MapDirectionsRoute,
  MapOfflineRoute: MapOfflineRoute,
  MapIndexRoute: MapIndexRoute,
  MapPlaceIdRoute: MapPlaceIdRoute,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
