/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/_map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MapIndexRouteImport } from './routes/_map/index'
import { Route as MapDirectionsRouteImport } from './routes/_map/directions'
import { Route as MapHistoryRouteImport } from './routes/_map/history'
import { Route as MapMapRouteImport } from './routes/_map/map'
import { Route as MapOfflineRouteImport } from './routes/_map/offline'
import { Route as MapSettingsRouteImport } from './routes/_map/settings'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as MapPlaceIdRouteImport } from './routes/_map/place.$id'
import { Route as ApiTrafficZXYRouteImport } from './routes/api/traffic.$z.$x.$y'

const MapRoute = MapRouteImport.update({
  id: '/_map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapRoute,
} as any)
const MapDirectionsRoute = MapDirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => MapRoute,
} as any)
const MapHistoryRoute = MapHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MapRoute,
} as any)
const MapMapRoute = MapMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => MapRoute,
} as any)
const MapOfflineRoute = MapOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => MapRoute,
} as any)
const MapSettingsRoute = MapSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MapRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MapPlaceIdRoute = MapPlaceIdRouteImport.update({
  id: '/place/$id',
  path: '/place/$id',
  getParentRoute: () => MapRoute,
} as any)
const ApiTrafficZXYRoute = ApiTrafficZXYRouteImport.update({
  id: '/api/traffic/$z/$x/$y',
  path: '/api/traffic/$z/$x/$y',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MapIndexRoute
  '/auth': typeof AuthRoute
  '/directions': typeof MapDirectionsRoute
  '/history': typeof MapHistoryRoute
  '/map': typeof MapMapRoute
  '/offline': typeof MapOfflineRoute
  '/settings': typeof MapSettingsRoute
  '/share/$token': typeof ShareTokenRoute
  '/place/$id': typeof MapPlaceIdRoute
  '/api/traffic/$z/$x/$y': typeof ApiTrafficZXYRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/directions': typeof MapDirectionsRoute
  '/history': typeof MapHistoryRoute
  '/map': typeof MapMapRoute
  '/offline': typeof MapOfflineRoute
  '/settings': typeof MapSettingsRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof MapIndexRoute
  '/place/$id': typeof MapPlaceIdRoute
  '/api/traffic/$z/$x/$y': typeof ApiTrafficZXYRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_map': typeof MapRouteWithChildren
  '/auth': typeof AuthRoute
  '/_map/directions': typeof MapDirectionsRoute
  '/_map/history': typeof MapHistoryRoute
  '/_map/map': typeof MapMapRoute
  '/_map/offline': typeof MapOfflineRoute
  '/_map/settings': typeof MapSettingsRoute
  '/share/$token': typeof ShareTokenRoute
  '/_map/': typeof MapIndexRoute
  '/_map/place/$id': typeof MapPlaceIdRoute
  '/api/traffic/$z/$x/$y': typeof ApiTrafficZXYRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/directions'
    | '/history'
    | '/map'
    | '/offline'
    | '/settings'
    | '/share/$token'
    | '/place/$id'
    | '/api/traffic/$z/$x/$y'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/directions'
    | '/history'
    | '/map'
    | '/offline'
    | '/settings'
    | '/share/$token'
    | '/'
    | '/place/$id'
    | '/api/traffic/$z/$x/$y'
  id:
    | '__root__'
    | '/_map'
    | '/auth'
    | '/_map/directions'
    | '/_map/history'
    | '/_map/map'
    | '/_map/offline'
    | '/_map/settings'
    | '/share/$token'
    | '/_map/'
    | '/_map/place/$id'
    | '/api/traffic/$z/$x/$y'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MapRoute: typeof MapRouteWithChildren
  AuthRoute: typeof AuthRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiTrafficZXYRoute: typeof ApiTrafficZXYRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_map': {
      id: '/_map'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map/': {
      id: '/_map/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/directions': {
      id: '/_map/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof MapDirectionsRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/history': {
      id: '/_map/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof MapHistoryRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/map': {
      id: '/_map/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapMapRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/offline': {
      id: '/_map/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof MapOfflineRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/settings': {
      id: '/_map/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MapSettingsRouteImport
      parentRoute: typeof MapRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map/place/$id': {
      id: '/_map/place/$id'
      path: '/place/$id'
      fullPath: '/place/$id'
      preLoaderRoute: typeof MapPlaceIdRouteImport
      parentRoute: typeof MapRoute
    }
    '/api/traffic/$z/$x/$y': {
      id: '/api/traffic/$z/$x/$y'
      path: '/api/traffic/$z/$x/$y'
      fullPath: '/api/traffic/$z/$x/$y'
      preLoaderRoute: typeof ApiTrafficZXYRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MapRouteChildren {
  MapDirectionsRoute: typeof MapDirectionsRoute
  MapHistoryRoute: typeof MapHistoryRoute
  MapMapRoute: typeof MapMapRoute
  MapOfflineRoute: typeof MapOfflineRoute
  MapSettingsRoute: typeof MapSettingsRoute
  MapIndexRoute: typeof MapIndexRoute
  MapPlaceIdRoute: typeof MapPlaceIdRoute
}

const MapRouteChildren: MapRouteChildren = {
  MapDirectionsRoute: MapDirectionsRoute,
  MapHistoryRoute: MapHistoryRoute,
  MapMapRoute: MapMapRoute,
  MapOfflineRoute: MapOfflineRoute,
  MapSettingsRoute: MapSettingsRoute,
  MapIndexRoute: MapIndexRoute,
  MapPlaceIdRoute: MapPlaceIdRoute,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MapRoute: MapRouteWithChildren,
  AuthRoute: AuthRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiTrafficZXYRoute: ApiTrafficZXYRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
